name: Test CD

on:
  push:
    branches: [ main ]

env:
  SERVER_HOST: 13.127.106.130
  SERVER_USERNAME: ubuntu
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - name: Connect to server and deploy changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd ~/projects/Tur_Agent_API
          git pull
          npm install
          npx prisma migrate dev
          npx prisma generate
          npm run build
          pm2 restart tur-agent
